#!/bin/sh

mount /dev/sda3 /sysroot/usr
exit 0

for mountUnit in $(ls /sysroot/etc/systemd/system/usr*.mount) do  

WHERE=$(awk -F= '/^Where=/ { print $2}' "$mountUnit")
FSTYPE=$(awk -F= '/^Type=/ { print $2}' "$mountUnit")
DEVICE=$(awk -F= '/^What=/ { print $2}' "$mountUnit")
OPTIONS=$(awk -F= '/^Options=/ { print $2}' "$mountUnit") 

DEVNAME=$(systemd-escape -p "$DEVICE")
# create the mount unit in ramdisk
{
echo "[Unit]"
echo "Before=initrd-root-fs.target"
echo "Requires=systemd-fsck@${DEVNAME}.service"
echo "After=sysroot.mount"
echo "[Mount]"
echo "Where=/sysroot$WHERE"
echo "What=$DEVICE"
echo "Options=$OPTIONS"
echo "Type=$FSTYPE"
} > /etc/systemd/system/sysroot-$(basename $mountUnit)

systemctl -q add-wants initrd-fs.target sysroot-$(basename $mountUnit).mount
done
